### ISSUE TITLE
Valid poly out of range

### ISSUE THREAD

**Issue by Viermusketiere** [madler/crcany#12]
When using the poly
`width=12 poly=0x80e init=0x000 refin=false refout=false xorout=0x000 check=0xf5b residue=0x000 name="CRC-12/DECT"`
crcadd returns:

> CRC-12/DECT: poly out of range
> CRC-12/DECT is an unusable model -- skipping

When using the poly `0x80f`, crcadd works without problems.

The given poly `0x80e` should be working fine, it is not exceeding the allowed width or any other constraints.

**Comment by madler** [comment]
There is another constraint you are not considering. A valid polynomial must be odd. `0x80e` is even.

**Comment by Viermusketiere** [comment]
Is there any way to make even polynomials work with crcany?
A needed crc computation relies on the given polynomial `0x80e` defined by a communication standard.

**Comment by madler** [comment]
Then you are interpreting the standard incorrectly or there is an error. Without seeing the standard, I can only guess that either `0x80e` is a typo (since `0x80f` is in fact a common 12-bit CRC polynomial), or that the CRC is reflected, with `0x80e` being what is exclusive or'ed when the low bit is one. In the latter case, the polynomial would actually be `0x701`, or _x<sup>12</sup>+x<sup>10</sup>+x<sup>9</sup>+x<sup>8</sup>+1_.
